# Generated by Django 6.0 on 2025-12-20 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ward',
            field=models.CharField(blank=True, choices=[('1', 'Ward 1'), ('2', 'Ward 2'), ('3', 'Ward 3'), ('4', 'Ward 4'), ('5', 'Ward 5'), ('6', 'Ward 6'), ('7', 'Ward 7'), ('8', 'Ward 8'), ('9', 'Ward 9'), ('10', 'Ward 10'), ('11', 'Ward 11'), ('12', 'Ward 12'), ('13', 'Ward 13'), ('14', 'Ward 14'), ('15', 'Ward 15')], help_text='Your ward number (1-15)', max_length=2, null=True),
        ),
    ]
