# Generated by Django 6.0 on 2025-12-20 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(choices=[('1', 'Ward 1'), ('2', 'Ward 2'), ('3', 'Ward 3'), ('4', 'Ward 4'), ('5', 'Ward 5'), ('6', 'Ward 6'), ('7', 'Ward 7'), ('8', 'Ward 8'), ('9', 'Ward 9'), ('10', 'Ward 10'), ('11', 'Ward 11'), ('12', 'Ward 12'), ('13', 'Ward 13'), ('14', 'Ward 14'), ('15', 'Ward 15')], help_text='Select your ward number (1-15)', max_length=2)),
                ('category', models.CharField(choices=[('Road Maintenance', 'Road Maintenance'), ('Street Light', 'Street Light'), ('Water Supply', 'Water Supply'), ('Sanitation', 'Sanitation'), ('Traffic', 'Traffic'), ('Parks', 'Parks & Recreation'), ('Other', 'Other')], max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='complaints/')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'db_table': 'complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='complaints_status_f38b8e_idx'), models.Index(fields=['ward', 'status'], name='complaints_ward_e9b675_idx')],
            },
        ),
    ]
