# Generated by Django 6.0 on 2026-02-14 12:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_remark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='priority',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Urgent', 'Urgent')], default='Normal', help_text='Priority level - Auto-flagged as Urgent after 7 days', max_length=10),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['priority', 'status'], name='complaints_priorit_54b0b9_idx'),
        ),
    ]
